version: "3.8"
services:
  server: 
    build: "./."
    container_name: "server"
    env_file: 
      - .env
    ports: 
      - "${PORT}:${PORT}"
    depends_on: 
      database:
        condition: service_healthy
  database:
    image: "postgres:12"
    restart: "always"
    env_file: 
      - .env
    container_name: "${DB_HOSTNAME}"
    ports: 
      - "${DB_EXPOSED_PORT}:5432"
    environment: 
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  database:
     